# -*- coding: utf-8 -*-
"""Amanjakhetiya_9918103209_F8_OSS_LAB5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/167-lNTrJWegoQ2vQUKKkjHtzpBZcyIAe
"""

# Github Link : https://github.com/Amanjakhetiya/OSS_LAB_5

import matplotlib.pyplot as plt
import numpy as np

# 1
X=np.linspace(-np.pi,np.pi,256,endpoint=True)
C,S=np.cos(X),np.sin(X)

plt.plot(X,C)
plt.plot(X,S)
plt.show()

# 2
plt.figure(figsize=(8,6),dpi=80)
plt.subplot(1,1,1)

plt.plot(X,C,color='blue',linewidth=1.0,linestyle='-')
plt.plot(X,S,color='green',linewidth=1.0,linestyle='-')

plt.xlim(-4.0,4.0)
plt.xticks(np.linspace(-4,4,9,endpoint=True))

plt.ylim(-1.0,1.0)
plt.yticks(np.linspace(-1,1,5,endpoint=True))

plt.savefig("exercise_2.png",dpi=72)

# 3

#Adding legends
plt.plot(X,C,color='blue',linewidth=2.5,linestyle='-',label='cosine')
plt.plot(X,S,color='green',linewidth=2.5,linestyle='-',label='sine')

plt.legend(loc='upper left')

# 4

# Regular Plots
n=256
X=np.linspace(-np.pi,np.pi,n,endpoint=True)
Y=np.sin(2*X)

plt.plot(X, Y + 1, color='blue', alpha=1.00)
plt.plot(X, Y - 1, color='blue', alpha=1.00)

# 5

#Scatter plot

n=1024

X=np.random.normal(0,1,n)
Y=np.random.normal(0,1,n)

plt.scatter(X,Y)

# 6

#Bar Chart

n = 12
X = np.arange(n)
Y1 = (1 - X / float(n)) * np.random.uniform(0.5, 1.0, n)
plt.bar(X, +Y1, facecolor='#9999ff', edgecolor='black')
plt.show()
Y2 = (1 - X / float(n)) * np.random.uniform(0.5, 1.0, n)
plt.bar(X, -Y2, facecolor='#ff9999', edgecolor='black')
plt.show()

"""## Practice Questions

#### Q1.
"""

X = np.linspace(-np.pi,np.pi,7,endpoint=True)

SIN=np.sin(X)
COS=np.cos(X)
TAN=np.tan(X)
COT=np.arctan(TAN)
SEC=np.arccos(COS)
COSEC=np.arcsin(SIN)

plt.figure(figsize=(8,5),dpi=80)

plt.plot(X,TAN,color='blue',linewidth=2.5,linestyle='-',label='tan')
plt.plot(X,COT,color='green',linewidth=2.5,linestyle='--',label='cot')
plt.plot(X,SEC,color='red',linewidth=2.5,linestyle='-.',label='sec')
plt.plot(X,COSEC,color='black',linewidth=2.5,linestyle=':',label='cosec')

plt.legend(loc='upper center')

"""### Q2."""

A=np.array([2,5,8,5])
B=np.array([3,2,5,7])
lab=['A','B','C','D']

x1 = np.arange(len(A))
x2 = [x + 0.25 for x in x1]

plt.bar(x1,A,width=0.25,label='result1')
plt.bar(x2,B,width=0.25,label='result2')

plt.xticks(x2,lab)

plt.show()

